### ISSUE TITLE
Blocked: OceanBase Restore From S3

### ISSUE THREAD

**Issue by zhaohuxing** [zhaohuxing/datatalk#3]
**Describe  the question**
The restore was blocked but without resulting in failure

Case: The backup is 200MB in size, but it has been 17 hours since the restoration started and it still hasn't been completed yet.

**Comment by zhaohuxing** [comment]
Try to solve the problem and read some articles.

- https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000001050226
- https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000001050221
- https://www.oceanbase.com/docs/enterprise-oceanbase-database-cn-10000000000360549
- https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000001573805

go on...

**Comment by zhaohuxing** [comment]
Read docs: Manage -> Troubleshooting -> Backup and restore -> Physical restore failures
https://en.oceanbase.com/docs/common-oceanbase-database-10000000001715116

**Step 1:**
```
mysql> SELECT * FROM oceanbase.GV$OB_SERVER_SCHEMA_INFO WHERE tenant_id=1012;
+--------------+----------+-----------+--------------------------+-------------------------+--------------+-------------+----------------------------+
| SVR_IP       | SVR_PORT | TENANT_ID | REFRESHED_SCHEMA_VERSION | RECEIVED_SCHEMA_VERSION | SCHEMA_COUNT | SCHEMA_SIZE | MIN_SSTABLE_SCHEMA_VERSION |
+--------------+----------+-----------+--------------------------+-------------------------+--------------+-------------+----------------------------+
| 10.x.x.1 |     2882 |      1012 |                        1 |                       1 |            4 |        1150 |                         -1 |
| 10.x.x.2 |     2882 |      1012 |                        1 |                       1 |            4 |        1150 |                         -1 |
| 10.x.x.3 |     2882 |      1012 |                        1 |                       1 |            4 |        1150 |                         -1 |
+--------------+----------+-----------+--------------------------+-------------------------+--------------+-------------+----------------------------+
```
the schema is not refreshed and you must search the observer.log file to continue with the troubleshooting.

**Step 2:**
```
./observer.log:234422:[2024-12-25 15:28:52.342882] INFO  [SHARE.SCHEMA] refresh_tenant_schema (ob_multi_version_schema_service.cpp:2803) [574140][SerScheQueue1][T0][YB420A8705A6-000629FB83E2C707-0-0] [lt=9] [REFRESH_SCHEMA] start to refresh and add schema by tenant(tenant_id=1012)
./observer.log:234423:[2024-12-25 15:28:52.342895] INFO  [SHARE.SCHEMA] refresh_tenant_schema (ob_multi_version_schema_service.cpp:2849) [574140][SerScheQueue1][T0][YB420A8705A6-000629FB83E2C707-0-0] [lt=8] [REFRESH_SCHEMA] tenant schema is not ready, just skip(ret=-5627, ret="OB_SCHEMA_EAGAIN", tenant_id=1012, refresh_schema_status={tenant_id:1012, snapshot_timestamp:0, readable_schema_version:0})
./observer.log:234424:[2024-12-25 15:28:52.342909] INFO  [SHARE.SCHEMA] refresh_tenant_schema (ob_multi_version_schema_service.cpp:2896) [574140][SerScheQueue1][T0][YB420A8705A6-000629FB83E2C707-0-0] [lt=12] [REFRESH_SCHEMA] end refresh and add schema by tenant(ret=-5627, ret="OB_SCHEMA_EAGAIN", tenant_id=1012, cost=18)
./observer.log:234425:[2024-12-25 15:28:52.342921] WDIAG [SHARE.SCHEMA] operator() (ob_multi_version_schema_service.cpp:2545) [574140][SerScheQueue1][T0][YB420A8705A6-000629FB83E2C707-0-0] [lt=10][errcode=0] fail to refresh tenant schema(tmp_ret=-5627, tenant_id=1012)
./observer.log:234426:[2024-12-25 15:28:52.342933] INFO  [SHARE.SCHEMA] refresh_and_add_schema (ob_multi_version_schema_service.cpp:2580) [574140][SerScheQueue1][T0][YB420A8705A6-000629FB83E2C707-0-0] [lt=10] [REFRESH_SCHEMA] end refresh and add schema(ret=-5627, ret="OB_SCHEMA_EAGAIN", tenant_ids=[], cost=35373)
./observer.log:234427:[2024-12-25 15:28:52.342945] WDIAG [SERVER] process_refresh_task (ob_server_schema_updater.cpp:303) [574140][SerScheQueue1][T0][YB420A8705A6-000629FB83E2C707-0-0] [lt=10][errcode=-5627] fail to refresh and add schema(ret=-5627, ret="OB_SCHEMA_EAGAIN")
./observer.log:234428:[2024-12-25 15:28:52.342954] INFO  [SERVER] process_refresh_task (ob_server_schema_updater.cpp:309) [574140][SerScheQueue1][T0][YB420A8705A6-000629FB83E2C707-0-0] [lt=8] [REFRESH_SCHEMA] end refresh schema with new mode, (ret=-5627, ret="OB_SCHEMA_EAGAIN", tenant_ids=[], used time=35415)
./observer.log:234429:[2024-12-25 15:28:52.342971] WDIAG [SERVER] batch_process_tasks (ob_server_schema_updater.cpp:230) [574140][SerScheQueue1][T0][YB420A8705A6-000629FB83E2C707-0-0] [lt=10][errcode=-5627] fail to process refresh task(ret=-5627, ret="OB_SCHEMA_EAGAIN", tasks.at(0)={type:1, did_retry:true, schema_info:{schema_version:1735111455811176, tenant_id:1, sequence_id:36283883719813}})
```

**Step 3:**
Only know that the schema hasn't been refreshed. I don't know anything else.

**Step 4:**
Re-back up and restore. Let's see if we can find any clues.
```
alter system noarchivelog tenant=tenant_test;

alter system archivelog tenant=tenant_test;

mc rm cdb/cdb -r --force

ALTER SYSTEM SET LOG_ARCHIVE_DEST='LOCATION=s3://cdb/test/archivelog/1010?host=<>&access_id=<>&access_key=<>&delete_mode=delete' tenant=tenant_test;

SELECT * FROM oceanbase.CDB_OB_ARCHIVELOG\G

ALTER SYSTEM SET DATA_BACKUP_DEST='s3://cdb/test/1010/tenant_test?host=<>&access_id=<>&access_key=<>' tenant=tenant_test;

alter system backup tenant=tenant_test;

ALTER SYSTEM RESTORE tenant_restore_test FROM 's3://cdb/test/1010/tenant_test?host=<>&access_id=<>&access_key=<>,s3://cdb/test/archivelog/1010?host=<>&access_id=<>&access_key=<>' WITH 'pool_list=pool_recover&concurrency=50';

ALTER SYSTEM CANCEL RESTORE tenant_restore_test;

DROP TENANT tenant_restore_test;

SELECT * FROM oceanbase.CDB_OB_RESTORE_PROGRESS\G

ALTER SYSTEM CANCEL RESTORE tenant_restore_test;
```
The result is the same as that in Step 2.

**Step 5:**
Backup and recovery are feasible on other S3

**Step 6:**
Re-restore, Observe the S3 log at the same time.
```
ALTER SYSTEM RESTORE tenant_restore_test FROM 's3://cdb/test/1010/tenant_test?host=<>&access_id=<>&access_key=<>,s3://cdb/test/archivelog/1010?host=<>&access_id=<>&access_key=<>' WITH 'pool_list=pool_recover&concurrency=50';
```
It was found that the Head requests had been being processed all the time.

Looking into the object name of the Head Request in depth, it was found that it was just a folder path rather than a complete Object name. And the head Object also returned normally.

eg: `test/archivelog/1010/piece_d1005r2p2/logstream_1001/log/127.obarc` is dir
```
Head test/archivelog/1010/piece_d1005r2p2/logstream_1001/log/127.obarc
....
Head test/archivelog/1010/piece_d1005r2p2/logstream_1001/log/1xxx.obarc
```
```
~ ls test/archivelog/1010/piece_d1005r2p2/logstream_1001/log/127.obarc
-rw-rw-rw- 1 work work 41964190 Dec 25 17:15 @APD_PART@0-41964190.obarc
-rw-rw-rw- 1 work work      723 Dec 25 17:15 @APD_PART@41964190-41964913.obarc
-rw-rw-rw- 1 work work   146064 Dec 25 17:17 @APD_PART@41964913-42110977.obarc
-rw-rw-rw- 1 work work   145210 Dec 25 17:19 @APD_PART@42110977-42256187.obarc
-rw-rw-rw- 1 work work   145820 Dec 25 17:21 @APD_PART@42256187-42402007.obarc
```
So I guess that it might be the unexpected behavior of the Head Object that caused this problem.

**Comment by zhaohuxing** [comment]
When I fixed the issue regarding the head object, the restore was successful.

```
*************************** 1. row ***************************
            TENANT_ID: 1026
                JOB_ID: 15
   RESTORE_TENANT_NAME: tenant_restore_test
     RESTORE_TENANT_ID: 1026
    BACKUP_TENANT_NAME: tenant_test
      BACKUP_TENANT_ID: 1010
   BACKUP_CLUSTER_NAME: ob425
           BACKUP_DEST: s3://cdb/test/1010/tenant_test?host=<>&access_id=<>&access_key=<>,s3://cdb/test/archivelog/1010?host=<>&access_id=<>&access_key=<>
           RESTORE_SCN: 1735125096581257004
   RESTORE_SCN_DISPLAY: 2024-12-25 19:11:36.581257
        RESTORE_OPTION: pool_list=pool_recover&concurrency=50
       START_TIMESTAMP: 2024-12-25 20:31:48.500637
      FINISH_TIMESTAMP: 2024-12-25 20:42:17.721900
                STATUS: SUCCESS
     BACKUP_PIECE_LIST: s3://cdb/test/archivelog/1010/piece_d1005r2p2?host=<>&access_id=<>&access_key=<>
       BACKUP_SET_LIST: s3://cdb/test/1010/tenant_test/backup_set_2_full?host=<>&access_id=<>&access_key=<>
BACKUP_CLUSTER_VERSION: 17180001536
              LS_COUNT: 4
       FINISH_LS_COUNT: 0
          TABLET_COUNT: 1323
   FINISH_TABLET_COUNT: 1323
           TOTAL_BYTES: 121653051
   TOTAL_BYTES_DISPLAY: 116.02MB
          FINISH_BYTES: 0
  FINISH_BYTES_DISPLAY: 0.00MB
           DESCRIPTION: NULL
               COMMENT:
```
